cache-dir = ".ruff_cache"
output-format = "grouped"

line-length = 120
src = [".", "apps/*/services/*/src", "src/"]

[format]
docstring-code-format = true
line-ending = "lf"

[lint.pycodestyle]
ignore-overlong-task-comments = true

[lint]
task-tags = ["TODO"]

select = ["ERA", "FAST", "ANN", "ASYNC", "S", "BLE", "FBT", "B", "A", "COM",
  "C4", "DTZ", "T10", "DJ", "EM", "EXE", "FIX", "INT", "ISC", "ICN", "LOG", "G",
  "INP", "PIE", "T20", "PYI", "PT", "Q", "RSE", "RET", "SLF", "SIM", "SLOT", "TID",
  "TC", "ARG", "PTH", "FLY", "I", "C90", "NPY", "PD", "N", "PERF", "E", "W",
  "D", "F", "PGH", "PL", "UP", "FURB", "RUF", "TRY"]
ignore = ["ANN002", "ANN003", "ANN401", "D100", "D101", "D102", "D103", "D104",
  "D105", "D106", "D107", "COM812", "D203", "D213", "D400", "D401", "D404", "D415", "FIX002"]

[lint.flake8-tidy-imports]
ban-relative-imports = "parents"

[lint.per-file-ignores]
"*/test_*.py" = ["S101", "ANN201", "ANN001", "PLR0913"]
"*/tests/*.py" = ["S101", "ANN201", "ANN001", "PLR0913", "INP001", "B017", "PT011"]
"scripts/*.py" = ["T20", "BLE001"]
"*/tests/*" = ["INP001", "SLF001", "PLR2004"]
"examples/**/*.py" = ["INP001", "T20"]
"src/semfs/cli.py" = ["FBT001", "FBT002", "PLR0913"]
"src/semfs/search.py" = ["FBT001", "FBT002"]
